# Site settings
title: Abra-code-abra
subtitle: alias yolo='git commit -am "DEAL WITH IT" && git push -f origin master'
description: > # this means to ignore newlines until "baseurl:"
  SMASH IT OUT, gracefully.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tobyreid.github.io/" # the base hostname & protocol for your site
twitter_username: reidtoby
github_username: tobyreid

# Build settings
markdown: kramdown
highlighter: null
