# Site settings
title: Abra-code-abra
subtitle: Make it code
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tobyreid.github.io/" # the base hostname & protocol for your site
twitter_username: reidtoby
github_username: tobyreid

# Build settings
markdown: kramdown
highlighter: null
